name: Release
on: [ workflow_dispatch ] # Manual trigger
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 21
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - run: ./gradlew checkLicenses generateQmj --parallel --stacktrace
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      - run: ./gradlew build publish --stacktrace
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
  tag:
    runs-on: ubuntu-22.04
    outputs:
      output1: ${{ steps.getver.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Current Version
        id: getver
        run: echo version=$(grep -zoP '(GLUON_VERSION(?:(?!GLUON_VERSION)[\s\S])*?\K(?:(\d+)\.)?(?:(\d+)\.)?(?:(\d+)\.\d+)(-[a-z]*)?(\.[0-9]))?' build-logic/src/main/java/gluon/internal/Versions.java) >> "$GITHUB_OUTPUT"
      - name: Create Tag+Release
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ steps.getver.outputs.version }}',
              sha: context.sha
            })
